-- =============== FRESH START FOR COURSE 1 ===============
-- Clear every stored weekly plan (all were generated by the old build/flow/
-- stretch fallback during testing). Plans regenerate automatically the next
-- time each student opens the app — and from Mon Sep 7 they come from the
-- authored Course 1 curriculum, not the generator.
--
-- Practice history is untouched: practice_logs, song_progress, attendance
-- and recordings all keep their data. Only the plan rows (and their per-
-- segment checkmarks, which belonged to test plans) are removed.

DELETE FROM public.weekly_plan_sessions;
